### ISSUE TITLE
.vs folder wasn't ignored

### ISSUE THREAD

**Issue by bulfonjf** [Likhit/Docker-With-ASP-Core-and-MySQL#1]
I downloaded the code and moved the .env file to the root directory of the project.
Then I opened a CMD with administrator permissions and I execute this command:

C:\Users\Fran\Downloads\Docker-With-ASP-Core-and-MySQL-master\Docker-With-ASP-Core-and-MySQL-master>docker-compose -f .\Docker\docker-compose.yml build --no-cache

This is the result:

Building builder
Traceback (most recent call last):
  File "site-packages\docker\utils\build.py", line 96, in create_archive
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Fran\\Downloads\\Docker-With-ASP-Core-and-MySQL-master\\Docker-With-ASP-Core-and-MySQL-master\\.vs\\ContainerProd\\v15\\Server\\sqlite3\\db.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "docker-compose", line 6, in <module>
  File "compose\cli\main.py", line 71, in main
  File "compose\cli\main.py", line 127, in perform_command
  File "compose\cli\main.py", line 282, in build
  File "compose\project.py", line 378, in build
  File "compose\service.py", line 1067, in build
  File "site-packages\docker\api\build.py", line 154, in build
  File "site-packages\docker\utils\build.py", line 31, in tar
  File "site-packages\docker\utils\build.py", line 100, in create_archive
OSError: Can not read file in context: C:\Users\Fran\Downloads\Docker-With-ASP-Core-and-MySQL-master\Docker-With-ASP-Core-and-MySQL-master\.vs\ContainerProd\v15\Server\sqlite3\db.lock
[10332] Failed to execute script docker-compose

I am doing something wrong?

**Comment by Likhit** [comment]
Sorry, I didn't see this issue before. It might be too late, but for what it's worth, I tried to replicate your steps, but wasn't able to reproduce the error. I even tried it on a different machine with a fresh install of docker.

I guess the .vs folder was created because you opened the solution on Visual Studios. I think what's happening is that docker is trying to copy the .vs folder too. You should be able to use a dockerignore file to blacklist it (https://docs.docker.com/engine/reference/builder/#dockerignore-file). Placing this file in the root should prevent copying of the .vs folder.
